/**
 * 将 styles/ 模块拼接为插件根目录 styles.css（Obsidian 加载产物）。
 * 顺序：legacy 基线 → shell / composer / message / run-view / secondary
 * 新规则用选择器优先级覆盖，禁止新增 !important（宿主兼容除外）。
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const stylesDir = join(root, "styles");
const modules = [
  "legacy.css",
  "shell.css",
  "composer.css",
  "message.css",
  "run-view.css",
  "secondary.css",
];

const parts = [];
parts.push("/* AUTO-GENERATED by scripts/build-styles.mjs — do not edit styles.css directly */\n");
for (const name of modules) {
  const path = join(stylesDir, name);
  if (!existsSync(path)) {
    console.warn(`[build-styles] skip missing ${name}`);
    continue;
  }
  const body = readFileSync(path, "utf8").replace(/\r\n/g, "\n");
  parts.push(`\n/* ===== ${name} ===== */\n`);
  parts.push(body.endsWith("\n") ? body : `${body}\n`);
}

const out = join(root, "styles.css");
writeFileSync(out, parts.join(""), "utf8");
console.log(`[build-styles] wrote ${out} (${parts.join("").length} chars)`);
